import MenuSheet from '@/features/_components/sheet/MenuSheet';
import type { Metadata } from 'next';
import '../features/_styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <div>
          <MenuSheet userId={1}></MenuSheet>
          {children}
        </div>
      </body>
    </html>
  );
}
