import ChatButton from '@/features/_components/button/ChatButton';
import LogoutButton from '@/features/_components/button/LogoutButton';
import MenuSheet from '@/features/_components/sheet/menu/MenuSheet';
import type { Metadata } from 'next';
import '../features/_styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <div className=' relative min-h-screen'>
          <div className=' absolute top-[2%] left-[1%]'>
            <MenuSheet userId={1} />
          </div>
          <ChatButton />
          <LogoutButton />
          <div className=' border border-solid overflow-hidden rounded-2xl border-black w-4/5 h-[90%] fixed top-1/2 bottom-1/2 left-1/2 right-1/2 -translate-y-1/2 -translate-x-1/2'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
